### ISSUE TITLE
Fixed Length Practise Questions Keep Going

### ISSUE THREAD

**Issue by Jacrac04** [Jacrac04/DFM-Bot#1]
The bot keeps answering fixed length practice questions even after it has reached the 'end'. It has to manually be stopped by closing the program. This leads to a impossible score and different colour!

![image](https://user-images.githubusercontent.com/62761393/109059235-f0838a80-76db-11eb-867b-f1a5c6e1d883.png)

**Comment by TheGodOfNoodles** [comment]
it doesn't actually answer any questions it just says what type of question it is and does nothing

**Comment by Jacrac04** [comment]
This can be controlled it the v3.1.0 by entering the correct amount of questions.
