### ISSUE TITLE
executable contains a trojan.

### ISSUE THREAD

**Issue by throwaway129-webdev** [Jacrac04/DFM-Bot#12]
executable download contained a trojan. malwarebytes, spybot and windows picked it up immediately. 

do not know if this was intentional, and i do not know how this malware was packaged into this executable (which is open source??) but do not download this script.

**Comment by Jacrac04** [comment]
Hi @throwaway129-webdev, the executable is not a trojan. As I used pyinstaller to compile the .exe and I'm not an expert, a lot of antivirus will think its a trojan. I will try to find a way to fix this.
![image](https://user-images.githubusercontent.com/62761393/111532355-78016e00-875d-11eb-8799-c48af7e6c4a4.png)
However, if your antivirus picks it up as a trojan, I recommend you don't run it, instead, if you have python experience, you can download the source code and run it yourself. If you don't know how to you can run it online by forking [my repo on repl.it](https://repl.it/@Jacrac04/DFM-Bot#main.py)

**Comment by Jacrac04** [comment]
I have added a part about his to the README.md in this [commit.](https://github.com/Jacrac04/DFM-Bot/commit/f96907512008a3cabf80626118537cb2a4196c0e)
