### ISSUE TITLE
i got banned for doing the homework 

### ISSUE THREAD

**Issue by TheGodOfNoodles** [Jacrac04/DFM-Bot#16]
it banned me when i set it to auto submit a 15 question homework it said : Due to suspicious question-answering activity, your account has been automatically suspended. You will need to ask your teacher to contact DrFrostMaths support to explain the situation if you wish to have your account reinstated.

**Comment by Jacrac04** [comment]
Hi @TheGodOfNoodles. I am aware of this issue, I updated the README a few days ago and there is more about it [in this issue.](https://github.com/Jacrac04/DFM-Bot/issues/11#issuecomment-823115480)

**Comment by Jacrac04** [comment]
This has been fixed in [v4.0.0](https://github.com/Jacrac04/DFM-Bot/releases/tag/v4.0.0)
