### ISSUE TITLE
Source code (and school)

### ISSUE THREAD

**Issue by Tf0R24** [Jacrac04/DFM-Bot#26]
Just wondering, I saw in the source code that if your email address feild doesnt have an @ it will auto type "@utcportsmouth.org". Are you attending a utc college? because if you are, i think thats cool. I'm in year 12 at UTC leeds. Idrk why im saying this but i thought it was cool.

**Comment by Jacrac04** [comment]
Hi @Tf0R24,
Sorry for not responding, I'm just a bit cautious what I say on this Project. I do attend UTC Portsmouth! I'm not comfortable saying anymore of my personal details publicly, I hope you understand. But thank you for commenting anyway.
