### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Omie2221** [Jacrac04/DFM-Bot#28]
always comes up with "Invalid totalQnum or delay"

![image_2022-02-06_220606](https://user-images.githubusercontent.com/79924254/152703320-ce3379d4-7617-44af-9c56-3c44dd19f686.png)

**Comment by Omie2221** [comment]
But other than that it all looks legit
great work man

**Comment by Jacrac04** [comment]
Thank you, @Omie2221 
Unfortunately it looks like Dr Frost has fixed the underlying issue with his website and has restricted access to the check answer functions. I will investigate more over the next week, but it is not looking likely that I will be able to get this working again.

**Comment by Jacrac04** [comment]
I have found a new way and will get the bot working over the next few weeks!

**Comment by Omie2221** [comment]
Amazing job
Truly
