### ISSUE TITLE
https://www.drfrostmaths.com/homework/util-getassessmentattempt2

### ISSUE THREAD

**Issue by Zachariahphash** [Jacrac04/DFM-Bot#32]
Not working shows this message everytime
util-getassessmentattempt2.php?

**Comment by Jacrac04** [comment]
Hi, 
I believed this is the same as in Issue #30 which I fixed in pull request #31

I will leave this open till I have confirmed that and created a new release.

**Comment by Omie2221** [comment]
Now a new error which shows 
util-getassessmentattempt2.php?
Unexpected exception occurred: 'correctAnswer'

**Comment by Jacrac04** [comment]
Hi @Omie2221, 
Is this on the latest release or are you running the current source code in the main branch?

**Comment by yubi-ippon** [comment]
I also get this error, both on the latest release and the current source code

**Comment by ILikeToDraw** [comment]
> I also get this error, both on the latest release and the current source code

same here, the bot is practically unusable.

**Comment by Omie2221** [comment]
They both work fine for me and have worked fine for the past week
Just try and download the latest release @yubi-ippon @ILikeToDraw 
Great work again @Jacrac04

**Comment by Jacrac04** [comment]
@Omie2221  That's great news, I've been trying to recreate the issue all week!

I'll close this issue now and it can be reopened if necessary, or anyone can create a new issue and mark it as 'help wanted' if anyone needs it, I'm more than happy to help!

**Comment by Jacrac04** [comment]
I had forgotten to pull the latest version on replit. If you are using repl you may need to re fork it or you may be able to add this git repository and pull it from here, however I am not familiar with how replit works so I can not say for certain.

**Comment by Jacrac04** [comment]
I would like to correct myself, I have now managed to recreate the issue and I'm looking into a fix now

**Comment by ILikeToDraw** [comment]
the latest version is 5.0.0 right?

**Comment by ILikeToDraw** [comment]
> I would like to correct myself, I have now managed to recreate the issue and I'm looking into a fix now.
> 
> -- Edit -- I would like to correct myself again! It does work and I accidently was using an old version.

still having problems. 

Unexpected exception occurred: Expecting ',' delimiter: line 1 column 1270 (char 1269)

i am using version 5.0.0 on windows exe file

**Comment by Jacrac04** [comment]
Hi @ILikeToDraw , 
The latest "version" isn't actually a release, its the source code in the master branch of the repository. I have a few more features to finish tonight and tomorrow then I will make an actual release.  I can see how my use on incorrect terminology in this thread could have made this confusing.
