### ISSUE TITLE
Please update the online version

### ISSUE THREAD

**Issue by BChen233** [Jacrac04/DFM-Bot#35]
Hey Jacrac, cause the speacil internet case in China, there will have lot of issue running the code offline.
While I can run the online version of it.
![未命名1648740242](https://user-images.githubusercontent.com/60862358/161091554-f2a5f86e-a035-4283-937b-764baf897d19.png)

Thank You, This project really helps

**Comment by Jacrac04** [comment]
Hi @BChen233,
I'm not quite sure what you mean. Do you mean the version on replit isn't working? If so, when you click the version control tab does it show up as 'up to date with master'?
![image](https://user-images.githubusercontent.com/62761393/161263399-aa1141f5-80fb-4ed4-8cb6-93316a4e3a4d.png)

I recognise the error you shared as I have similar while trying to debug web requests and I still haven't managed to get it working while 'snooping' my own traffic.


  Jacob

**Comment by BChen233** [comment]
Sorry, Problem fixed, I thought that the online version was not working because the last time I checked its not working.

**Comment by Jacrac04** [comment]
No worries, @BChen233
