### ISSUE TITLE
Answer bug

### ISSUE THREAD

**Issue by maikeulol** [Jacrac04/DFM-Bot#6]
**Describe the bug**
I don't know if this is because I used it too much but the first time I did it, I got 100% (check attached screenshot)

Your bot is helping out a lot, keep tweaking it!

![bug](https://user-images.githubusercontent.com/79786336/109413323-ab45ae00-79a4-11eb-9f5d-dff413f43f97.png)

**Comment by Jacrac04** [comment]
Hi @maikeulol! I have managed to recreate the issue and I believe I have fixed it in [this commit in develp](https://github.com/Jacrac04/DFM-Bot/commit/2b8cecb7a75232b0c5f4ecd02502a376a7161149). I will hopefully be releasing this version within the next few days.

**Comment by Jacrac04** [comment]
A new version which has a fix for this issue has been released.
